name: Publish
on:
  push: {
    branches:
      - main
  }
  workflow_dispatch:
    inputs:
      release:
        description: 'major | minor | patch'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  publish-new-version:
    runs-on: ubuntu
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Build
        #run: yarn build
        run: |
          npm install
          npm run build
          ls -la
      - name: Publish New Version
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          git config --local user.email "tawasal"
          git config --local user.name "tawasal"
          #yarn version --new-version ${{github.event.inputs.release}} --no-git-tag-version
          #yarn publish --access public
          npm version --new-version ${{github.event.inputs.release}} --no-git-tag-version
          npm publish --access public
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          git commit -a -m "v${PACKAGE_VERSION}"
          git push
